<?php
namespace app\index\controller;

use think\App;
use think\Controller;
use think\Db;
use think\View;

class Base extends Controller{
//    public function __construct()
//    {
//        parent::__construct();
//    }
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $data = Db::name('setting')->find();
        $this->assign("setting",$data);
    }
}