<?php
namespace app\index\controller;

use think\Controller;


class UBase extends Controller{
//    public function __construct()
//    {
//        parent::__construct();
//
//    }
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        if(!session('username')){
            $this->redirect('/web/login');
        }
    }
}